- name: Ensure NGINX is installed
  apt: 
    name: "{{ nginx_package_name }}"
    state: present
  become: true

- name: Ensure NGINX is enabled and running
  service: 
    name: nginx
    enabled: true
    state: started
  become: true

- name: Configure NGINX
  template: 
    src: nginx.conf.j2
    dest: "{{ nginx_conf_file }}"
  become: true
  notify: 
    - restart nginx
